export const environment = {
    base: 'http://localhost:8080/api/v1/auth',
    profile: 'http://localhost:8080/api/v1/profile',
    categories: 'http://localhost:8080/api/v1/admin/category',
    brands: 'http://localhost:8080/api/v1/admin/brand',
    products: 'http://localhost:8080/api/v1/admin/product', 
    products_user: 'http://localhost:8080/api/v1/product',
    category_user: 'http://localhost:8080/api/v1/category',
    adminProducts: 'http://localhost:8080/api/v1/admin/product', 
    userProducts: 'http://localhost:8080/api/v1/product',
    userCategories: 'http://localhost:8080/api/v1/category',
    userBrands: 'http://localhost:8080/api/v1/brand',
    featured: 'http://localhost:8080/api/v1/admin/featured',
    base_url: 'http://localhost:8080/api/v1', 
};
